package my_types

import "github.com/google/uuid"

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    string    `json:"created_at"`
	IsNew        bool      `json:"is_new"` // the ID created will be replaced by an ID generated by PostgreSQL if IsNew == true
}

type Club struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	PlayerIDs map[uuid.UUID]string `json:"players"`
	TeamIDs   map[uuid.UUID]string `json:"teams"`
	IsNew     bool                 `json:"is_new"`
}

type Player struct {
	ID        uuid.UUID            `json:"id"`
	Firstname string               `json:"firstname"`
	Lastname  string               `json:"lastname"`
	Age       int                  `json:"age"`
	Ranking   int                  `json:"ranking"`
	Material  []string             `json:"material"`
	TeamIDs   map[uuid.UUID]string `json:"teams"`
	ClubIDs   map[uuid.UUID]string `json:"clubs"`
	IsNew     bool                 `json:"is_new"`
}

type Team struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	PlayerIDs map[uuid.UUID]string `json:"players"`
	ClubID    map[uuid.UUID]string `json:"clubs"`
	IsNew     bool                 `json:"is_new"`
}

type Database struct {
	Users           map[uuid.UUID]*User    `json:"users"`
	Clubs           map[uuid.UUID]*Club    `json:"clubs"`
	Teams           map[uuid.UUID]*Team    `json:"teams"`
	Players         map[uuid.UUID]*Player  `json:"players"`
	DeletedElements map[string][]uuid.UUID `json:"deleted_elements"` // store elements that need to be deleted on the PostgreSQL database
}
